# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cache.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cache.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61\x63he.proto\x12\x05\x63\x61\x63he\"\x17\n\x08\x43\x61\x63heKey\x12\x0b\n\x03key\x18\x01 \x01(\t\"4\n\tCacheItem\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x0b\n\x03ttl\x18\x03 \x01(\x05\"*\n\nCacheValue\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\x0c\"3\n\rCacheResponse\x12\"\n\x06status\x18\x01 \x01(\x0e\x32\x12.cache.CacheStatus\"\xa6\x01\n\nCacheStats\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\x0c\n\x04hits\x18\x02 \x01(\x05\x12\x0e\n\x06misses\x18\x03 \x01(\x05\x12\x11\n\tevictions\x18\x04 \x01(\x05\x12\x10\n\x08hit_rate\x18\x05 \x01(\x01\x12\x1a\n\x12memory_usage_bytes\x18\x06 \x01(\x03\x12\x18\n\x10max_memory_bytes\x18\x07 \x01(\x03\x12\x11\n\tmax_items\x18\x08 \x01(\x05\"\x07\n\x05\x45mpty*>\n\x0b\x43\x61\x63heStatus\x12\x1c\n\x18\x43\x41\x43HE_STATUS_UNSPECIFIED\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x32\xc3\x01\n\x0c\x43\x61\x63heService\x12)\n\x03Get\x12\x0f.cache.CacheKey\x1a\x11.cache.CacheValue\x12-\n\x03Set\x12\x10.cache.CacheItem\x1a\x14.cache.CacheResponse\x12/\n\x06\x44\x65lete\x12\x0f.cache.CacheKey\x1a\x14.cache.CacheResponse\x12(\n\x05Stats\x12\x0c.cache.Empty\x1a\x11.cache.CacheStatsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cache_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CACHESTATUS']._serialized_start=376
  _globals['_CACHESTATUS']._serialized_end=438
  _globals['_CACHEKEY']._serialized_start=22
  _globals['_CACHEKEY']._serialized_end=45
  _globals['_CACHEITEM']._serialized_start=47
  _globals['_CACHEITEM']._serialized_end=99
  _globals['_CACHEVALUE']._serialized_start=101
  _globals['_CACHEVALUE']._serialized_end=143
  _globals['_CACHERESPONSE']._serialized_start=145
  _globals['_CACHERESPONSE']._serialized_end=196
  _globals['_CACHESTATS']._serialized_start=199
  _globals['_CACHESTATS']._serialized_end=365
  _globals['_EMPTY']._serialized_start=367
  _globals['_EMPTY']._serialized_end=374
  _globals['_CACHESERVICE']._serialized_start=441
  _globals['_CACHESERVICE']._serialized_end=636
# @@protoc_insertion_point(module_scope)
